Repository 2manymws/rl, pull requests merged in 2023-08, with the labels that each got.

#3 Change the interface of Limiter
  rl.go
  rl_test.go
  testutil/limiter.go
Labels: minor, breaking-change

#5 Re-change the interface of Limiter.
  rl.go
  testutil/limiter.go
Labels: breaking-change

#7 Remove Limiter.Name
  rl.go
  testutil/limiter.go
Labels: minor, breaking-change

#8 If reqLimit is negative, it means no limit.
  rl.go
  rl_test.go
Labels: enhancement

#9 More information received when rate limits are exceeded.
  error.go
  rl.go
  testutil/limiter.go
Labels: minor, breaking-change

#11 Fix LimitError handling
  error.go
  rl.go
  testutil/limiter.go
Labels: bug, breaking-change

#15 Should put a default value in the statuscode.
  rl.go
  rl_test.go
  testutil/limiter.go
Labels: bug

#18 WriteHeader() is called before Write(). Also, it is not possible to write the header twice.
  rl.go
  rl_test.go
  testutil/limiter.go
Labels: bug

#20 Provide Limiter with a feature to ignore the next and following Limiters.
  rl.go
  rl_test.go
  testutil/limiter.go
Labels: enhancement, minor, breaking-change
